# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Creating complex column vectors

In [1]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)


Matrix:
 [[2 3]
 [1 4]]

Vector:
 [5 6]

Result of multiplication:
 [28 29]


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [ ]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [2]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


(array([[3.+3.j, 6.+0.j, 3.-3.j],
        [1.+1.j, 2.+5.j, 6.-2.j],
        [7.+3.j, 8.-2.j, 5.+3.j]]),
 array([[-2.-3.j, -4.+1.j, -0.-0.j],
        [-1.-1.j, -3.-3.j, -5.-0.j],
        [-4.-0.j, -6.+2.j, -1.+1.j]]),
 array([[-0.5+2.5j,  2.5+1.5j,  0. +0.j ],
        [ 0. +1.j ,  0. +3.j ,  2.5+2.5j],
        [ 2. +2.j ,  4. +2.j ,  1. +0.j ]]),
 array([[2.-3.j, 4.+1.j, 0.-0.j],
        [1.-1.j, 3.-3.j, 5.-0.j],
        [4.-0.j, 6.+2.j, 1.+1.j]]),
 array([[2.+3.j, 1.+1.j, 4.+0.j],
        [4.-1.j, 3.+3.j, 6.-2.j],
        [0.+0.j, 5.+0.j, 1.-1.j]]),
 array([[2.-3.j, 1.-1.j, 4.-0.j],
        [4.+1.j, 3.-3.j, 6.+2.j],
        [0.-0.j, 5.-0.j, 1.+1.j]]))

## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [ ]:
# Checking the dimension of matrix1
m1.shape

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [ ]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.

### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.


# Resolviendo ejercicios:
### JOHN SEBASTIAN PEÑA SANCHEZ.
# Ejercicio 1: Adición de vectores complejos.

Dado dos vectores complejos 
$$ v1 = \begin{bmatrix} 3 + 4i \\ 2 - 3i \end{bmatrix} $$ 
y 
$$ v2 = \begin{bmatrix} 1 - 2i \\ 5 + i \end{bmatrix} $$, 
encuentra su suma.


In [24]:
import numpy as np

# Definir los nuevos vectores como matrices
v1 = np.array([[3+4j],
               [2-3j]])

v2 = np.array([[1-2j],
               [5+1j]])

# Sumar los vectores
resultado = v1 + v2

# Imprimir resultado
print("El resultado de la suma de los dos vectores es:")
print(resultado)

El resultado de la suma de los dos vectores es:
[[4.+2.j]
 [7.-2.j]]


### El resultado de la suma de los dos vectores es:

$$
\begin{bmatrix}
4 + 2i \\
7 - 2i
\end{bmatrix}
$$

# Ejercicio 2: Inverso (aditivo) de un vector complejos.

Dado un vector complejo 
$$ v = \begin{bmatrix} 2 + 3i \\ -1 + 2i \end{bmatrix} $$, 
encuentra su inverso aditivo.

El inverso aditivo de un vector complejo se calcula multiplicando cada elemento del vector por -1.

In [25]:
import numpy as np

# Definir los nuevos vectores como matrices
v = np.array([[2+3j],
              [-1+2j]])

# Calcular el inverso aditivo
inverso = -v

# Imprimir resultado
print("El inverso aditivo del vector es:")
print(inverso)

El inverso aditivo del vector es:
[[-2.-3.j]
 [ 1.-2.j]]


### El resultado del inverso aditivo del vector es:

$$
\begin{bmatrix}
-2 - 3i \\
1 - 2i
\end{bmatrix}
$$

# Ejercicio 3: Multiplicación de un escalar por un vector complejo.
Dado un vector complejo 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 4i \end{bmatrix} $$
y un escalar $k = 2$, encuentra el producto de $k$ por el vector $v$.


In [26]:
import numpy as np

def multiplicacion_escalar_vector(escalar, vector):
    resultado_multiplicacion = np.multiply(escalar, vector)
    return resultado_multiplicacion

# Escalar dado
escalar = 2

# Vector complejo dado
vec = [2 + 3j, 1 - 4j]

# Realizar la multiplicación del escalar por el vector
resultado = multiplicacion_escalar_vector(escalar, vec)

# Imprimir resultado
print("Producto del escalar y el vector complejo:", resultado)

Producto del escalar y el vector complejo: [4.+6.j 2.-8.j]


El resultado de la multiplicación de un escalar por un vector complejo es:

$$
2 \cdot \begin{bmatrix} 2 + 3i \\ 1 - 4i \end{bmatrix} = \begin{bmatrix} 4 + 6i \\ 2 - 8i \end{bmatrix}
$$


# Ejercicio 4: Transpuesta de un Vector Complejo

Encuentra la transpuesta del vector complejo
$$ v = \begin{bmatrix} 5 + 2i \\ 1 - 3i \end{bmatrix} $$.

In [27]:
import numpy as np

# Definir el vector complejo
v = np.array([[5 + 2j],
              [1 - 3j]])

# Calcular la transpuesta del vector
resultado_transpuesta = np.transpose(v)

# Imprimir el resultado
print("Transpuesta del vector:")
print(resultado_transpuesta)

Transpuesta del vector:
[[5.+2.j 1.-3.j]]


### El resultado de la transpuesta del vector complejo es: 
$$ v^T = \begin{bmatrix} 5 + 2i & 1 - 3i \end{bmatrix} $$

# Ejercicio 5: Conjugado de un Vector Complejo

Calcula el conjugado del vector complejo. 
$$ v = \begin{bmatrix} 3 - 2i \\ 4 + 5i \end{bmatrix} $$


In [28]:
def conjugado_vector_complejo(vector):
    conjugado = [elemento.conjugate() for elemento in vector]
    return conjugado

# Vector complejo dado
v = [3 - 2j, 4 + 5j]

# Calcular el conjugado del vector complejo
resultado = conjugado_vector_complejo(v)

# Imprimir el resultado
print("El conjugado del vector complejo es:")
print(resultado)

El conjugado del vector complejo es:
[(3+2j), (4-5j)]


### El conjugado del vector complejo es:
$$ \begin{bmatrix} 3 + 2i \\ 4 - 5i \end{bmatrix} $$


# Ejercicio 6: Adjunta (Transpuesta Conjugada) de un Vector Complejo

Encuentra la adjunta (o transpuesta conjugada) del vector complejo.
$$ v = \begin{bmatrix} 2 + i \\ 4 - 3i \end{bmatrix} $$

In [29]:
import numpy as np

# Definir el vector complejo
v = np.array([[2 + 1j],
              [4 - 3j]])

# Encontrar la adjunta del vector complejo (transpuesta conjugada)
adjunta_v = np.conj(v.T)

# Imprimir la adjunta del vector complejo
print("La adjunta (transpuesta conjugada) del vector complejo es:")
print(adjunta_v)

La adjunta (transpuesta conjugada) del vector complejo es:
[[2.-1.j 4.+3.j]]


### La adjunta (transpuesta conjugada) del vector complejo es:

$$ v^\dagger = \begin{bmatrix} 2 - i & 4 + 3i \end{bmatrix} $$

# Ejercicio 7: Suma de Dos Matrices Complejas

Dadas dos matrices complejas 
$$ m1 = \begin{bmatrix} 3 + i & 4 - 2i \\ 1 + 2i & 5 \end{bmatrix} $$ 
y 
$$ m2 = \begin{bmatrix} 1 - 2i & 3 \\ 2i & 4 + 3i \end{bmatrix} $$
calcula su suma.

In [30]:
import numpy as np

def suma_matrices_complejas(matriz1, matriz2):
    return matriz1 + matriz2

# Definir las matrices complejas
m1 = np.array([[3 + 1j, 4 - 2j],
               [1 + 2j, 5]])

m2 = np.array([[1 - 2j, 3],
               [2j, 4 + 3j]])

# Calcular la suma de las matrices complejas
resultado = suma_matrices_complejas(m1, m2)

# Imprimir el resultado
print("La suma de las matrices complejas es:")
print(resultado)

La suma de las matrices complejas es:
[[4.-1.j 7.-2.j]
 [1.+4.j 9.+3.j]]


### La suma de las matrices complejas es:

$$
\begin{bmatrix} 4 - 1i & 7 - 2i \\ 1 + 4i & 9 + 3i \\ \end{bmatrix} $$


# Exercise 8: Negation of a Complex Matrix
Encuentra la negación de la matriz compleja 
$$ m = \begin{bmatrix} 3 + 2i & 1 \\ 2 - i & 4 - 3i \end{bmatrix} $$.


In [31]:
import numpy as np

# Definir la matriz compleja
m = np.array([[3 + 2j, 1],
              [2 - 1j, 4 - 3j]])

# Encontrar la negación de la matriz
negacion_m = -m

# Imprimir la solución
print("La negación de la matriz compleja m es:")
print(negacion_m)


La negación de la matriz compleja m es:
[[-3.-2.j -1.-0.j]
 [-2.+1.j -4.+3.j]]


### La negación de la matriz compleja es: 
$$ m = \begin{bmatrix} -3-2j & -1-0j \\ -2+1j & -4+3j \end{bmatrix} $$

 # Ejercicio 9: Multiplicación de una Matriz Compleja por un Escalar. 
Multiplica la matriz compleja
$$ m = \begin{bmatrix} 3 - 2i & 4 \\ 5 + 2i & 6 - 3i \end{bmatrix} $$
por el escalar complejo $$ 1 + i $$

In [32]:
import numpy as np

# Definir la matriz compleja
m = np.array([[3 - 2j, 4],
              [5 + 2j, 6 - 3j]])

# Definir el escalar complejo
escalar = 1 + 1j

# Multiplicar la matriz por el escalar
resultado = m * escalar

# Imprimir el resultado
print("El resultado de multiplicar la matriz compleja por el escalar complejo es:")
print(resultado)

El resultado de multiplicar la matriz compleja por el escalar complejo es:
[[5.+1.j 4.+4.j]
 [3.+7.j 9.+3.j]]


### El resultado de multiplicar la matriz compleja por el escalar complejo es: 
$$ m = \begin{bmatrix} 5 + 1i & 4 + 4i \\ 3 + 7i & 9 + 3i \end{bmatrix} $$


# Ejercicio 10: Conjugado de una Matriz Compleja
Calcula el conjugado de la matriz compleja
$$ m = \begin{bmatrix} 2 - i & 3 \\ 4 + i & 5 - 2i \end{bmatrix} $$

In [18]:
import numpy as np

# Definir la matriz compleja
m = np.array([[2 - 1j, 3],
              [4 + 1j, 5 - 2j]])

# Calcular el conjugado de la matriz
conjugado_m = np.conj(m)

# Imprimir el resultado
print("El conjugado de la matriz compleja es:")
print(conjugado_m)

El conjugado de la matriz compleja es:
[[2.+1.j 3.-0.j]
 [4.-1.j 5.+2.j]]


### El resultado de la matriz compleja conjugada es:
$$ m = \begin{bmatrix} 2 + i & 3 \\ 4 - i & 5 + 2i \end{bmatrix} $$

# Ejercicio 11: Transpuesta de una Matriz Compleja

Encuentra la transpuesta de la matriz compleja
$$ m = \begin{bmatrix} 2 + i & 3 - i \\ 4 + 2i & 5 \end{bmatrix} $$


In [19]:
import numpy as np

# Definir la matriz compleja
m = np.array([[2 + 1j, 3 - 1j],
              [4 + 2j, 5]])

# Calcular la transpuesta de la matriz
transpuesta_m = np.transpose(m)

# Imprimir el resultado
print("La transpuesta de la matriz compleja es:")
print(transpuesta_m)

La transpuesta de la matriz compleja es:
[[2.+1.j 4.+2.j]
 [3.-1.j 5.+0.j]]


### El resultado de la transpuesta de la matriz compleja es:
$$ m^T = \begin{bmatrix} 2 + i & 4 + 2i \\ 3 - i & 5 \end{bmatrix} $$

# Ejercicio 11: Transpuesta de una Matriz Compleja

Encuentra la transpuesta de la matriz compleja
$$ m = \begin{bmatrix} 2 + i & 3 - i \\ 4 + 2i & 5 \end{bmatrix} $$


# Ejercicio 12: Adjunta (Transpuesta Conjugada) de una Matriz Compleja

Calcula la adjunta (o transpuesta conjugada) de la matriz compleja
$$ m = \begin{bmatrix} 3 + 4i & 1 - 2i \\ 2 + i & 4 \end{bmatrix} $$

In [21]:
import numpy as np

# Definir la matriz compleja
m = np.array([[2 - 1j, 3],
              [4 + 2j, 5 - 1j]])

# Calcular la adjunta de la matriz
adjunta_m = np.conj(m.T)

# Imprimir el resultado
print("La adjunta de la matriz compleja es:")
print(adjunta_m)


La adjunta de la matriz compleja es:
[[2.+1.j 4.-2.j]
 [3.-0.j 5.+1.j]]


### La adjunta de la matriz compleja m es:
$$ m^\dagger = \begin{bmatrix} 2 + i & 4 - 2i \\ 3 & 5 + i \end{bmatrix} $$

# Ejercicio 13: Verificación de las Dimensiones de una Matriz

Determina las dimensiones de la matriz compleja
$$ m = \begin{bmatrix} 2 - 3i & 1 \\ 2i & 4 + 3i \end{bmatrix} $$.


In [22]:
import numpy as np

# Definir la matriz compleja
m = np.array([[2 - 3j, 1],
              [2j, 4 + 3j]])

# Obtener las dimensiones de la matriz
dimensiones = m.shape

# Imprimir las dimensiones
print("Las dimensiones de la matriz compleja son:", dimensiones)

Las dimensiones de la matriz compleja son: (2, 2)


### Las dimensiones de la matriz compleja son:
(2, 2)


# Ejercicio 14: Multiplicación de una Matriz Cuadrada Compleja por un Vector Columna Complejo

Multiplica la matriz cuadrada compleja
$$ m = \begin{bmatrix} 2 + i & 3 - 2i \\ 4 & 5 + i \end{bmatrix} $$ 
por el vector columna complejo
$$ v = \begin{bmatrix} 1 - i \\ 2 + 3i \end{bmatrix} $$

In [23]:
import numpy as np

# Definir la matriz compleja
m = np.array([[2 + 1j, 3 - 2j],
              [4, 5 + 1j]])

# Definir el vector complejo
v = np.array([[1 - 1j],
              [2 + 3j]])

# Multiplicar la matriz por el vector
resultado = np.dot(m, v)

# Imprimir el resultado
print("El resultado de multiplicar la matriz por el vector es:")
print(resultado)

El resultado de multiplicar la matriz por el vector es:
[[15. +4.j]
 [11.+13.j]]


### El resultado de multiplicar la matriz por el vector es:
$$ \begin{bmatrix} 15 + 4i \\ 11 + 13i \end{bmatrix} $$